config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'expenses#index'

  resources :expenses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  CATEGORIES = %w[Traveling Clothing Taxi Cafes Shops Other]

  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true

  scope :accessible_for, -> (user) { where(user:user) }
end

app/models/user.rb
class User < ApplicationRecord
   devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :expenses, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, :only => [:expenses,:show]
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    @current_user_expenses = Expense.all.accessible_for(current_user)
    @expenses = @current_user_expenses.order(sort_column + ' ' + sort_direction)
    render_xhr
  end

  def show
  end

  def new
    @expense = Expense.new
  end

  def edit
  end

  def create
    @expense = Expense.create(expense_params)
    redirect_to expense_path(@expense)
  end

  def update
    @expense.update(expense_params)
    redirect_to expense_path(@expense)
  end

  def destroy
    @expense.destroy
    redirect_to root_path
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params[:expense].permit(:title, :description, :category, :user_id, :amount, :created_at)
  end

  def sort_column
    params[:sort] || 'created_at'
  end

  def sort_direction
    params[:direction] || 'desc'
  end

  def render_xhr
    render layout: false if request.xhr?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, { sort: column,
                     direction: direction}, { remote: true }
  end

  def count_month_spend
    CurrentMonthQuery.new(@current_user_expenses).call.sum(:amount)
  end

  def count_showed_spend
    @expenses.reduce(0) { | sum, expense | sum + expense.amount }
  end

  def count_year_spend
    ExpensesAYearQuery.new(@current_user_expenses).call.sum(:amount)
  end
end

app/views/expenses/_form.haml
= form_with(model: @expense, remote: true, class: "new-article-form") do |form|
  - if user_signed_in?
    = form.hidden_field :user_id, required: true, value: current_user.id, class: "form-control"
  .card-body
    = form.label :title
    = form.text_field :title, required: true, class: "form-control"
  .card-body
    = form.label :description
    = form.text_area :description, required: true, class: "form-control"
  .card-body
    = form.label :category
    %br/
    = form.select :category, options_for_select(Expense::CATEGORIES, form.object.category), |
      {include_blank: true},                                                                      |
      required: true, class: "custom-select"                                                      |
  .card-body
    = form.label :amount, required: true
    $
    \#{form.text_field :amount, class: "form-control", required: true}
  .card-body
    = form.label :spent_in, required: true
    = form.text_field :created_at, required: true, class: "form-control", type: "date"
  .card-body
    = submit_tag "Submit", class: "btn btn-primary"
    = link_to  "Cancel", expenses_path,  title: 'Click to remove', class: "btn btn-secondary cancel-icon"

app/views/expenses/_index_expenses.haml
%tr
  %td
    %b
      = link_to expense.title,                  |
        expense,                                |
        title: "Click to show more information" |
      %b
  %td.cursor-info{:title => expense.description}
    = expense.description
  %td= expense.category
  %td
    $#{expense.amount.round}
  %td= expense.created_at.strftime("%B %d, %Y")
  %td= link_to "Delete",                     |
      expense,                               |
      title: "Click to delete this expense", |
      method: :delete,                       |
      data: { confirm: 'Are you sure?' }     |

app/views/expenses/edit.haml
.card.mt-4.mx-auto.w-50
  .card-body
    %h5.card-header Edit expense
    = render 'form', expense: @expense

app/views/expenses/index.haml
.card.mt-4.mx-auto
  .card-body.mb-10
    %h3.card-title.text-center
      Your expenses
    .text-right
      %a.btn.btn-success.add-new-icon{:href => new_expense_path} Add new
    %table#expenses_table.table.mt-4
      %thead
        %tr{:role => "row"}
          %th.sorting{"data-name" => "title"}= sortable "title"
          %th.sorting{"data-name" => "description"}= sortable "description"
          %th.sorting{"data-name" => "category"}= sortable "category"
          %th.sorting{"data-name" => "amount"}= sortable "amount"
          %th.sorting.sorting_desc{"data-name" => "created_at"}= sortable "created_at"
          %th
      %tbody#expenses
        - @expenses.each_with_index do | expense, i |
          = render partial: "index_expenses", locals: {expense: expense, i: i}
    %table#spending.table
      %tbody
        %tr
          %td Spending:
          %td
            Last Year: $#{count_year_spend}
          %td
            Last Month: $#{count_month_spend}

app/views/expenses/index.js.erb
var direction = "<%= sort_direction %>";
var opposite_direction = direction == "asc" ? "desc" : "asc";
var sort_column = "<%= sort_column %>";

$("#expenses > tr").remove();

<% @expenses.each_with_index do | expense, i | %>
$('#expenses').append("<%= j render('index_expenses', expense: expense, i: i) %>");
<% end %>

$("#expenses_table th.sorting_asc").removeClass("sorting_asc").addClass("sorting");
$("#expenses_table th.sorting_desc").removeClass("sorting_desc").addClass("sorting");
$(`#expenses_table th[data-name=${sort_column}]`).removeClass("sorting").addClass(`sorting_${direction}`);

var links = $('#expenses_table th a');
links.each(function (i, link) {
    var col_name = $(link).parent().data('name');
    var col_dir = sort_column == col_name ? opposite_direction : "asc";
    var new_href = `/expenses?direction=${col_dir}&amp;sort=${col_name}&amp`;
    $(link).attr('href', new_href);
})

app/views/expenses/new.haml
.card.expenses-form.mt-4.mx-auto.w-50
  .card-body
    %h5.card-header New expense
    = render 'form'

app/views/expenses/show.haml
.card.bg-light.mt-4.mx-auto.w-50
  .card-header.bg-white
    %b
      Expense №#{@expense.id}, created #{time_ago_in_words(@expense.created_at)} ago
  .card-body
    %p.card-text
      Title:
      %b= @expense.title
    %p.card-text
      Description:
      %b= @expense.description
    %p.card-text
      Category:
      %b= @expense.category
    %p.card-text
      Amount: $
      %b= @expense.amount
    %p.card-text
      Spent in:
      %b= @expense.created_at
  %p.mx-auto
    - user_id = !user_signed_in? || current_user.id; if @expense.user_id == user_id then
      %button.btn.btn-success.btn-sm{:onclick => "copyToClipboard()"} Copy link
      = link_to  "Delete", expense_path(@expense), |
          method: :delete,                            |
          data: { confirm: 'Are you sure?'},          |
        class: "btn btn-danger btn-sm"                |
      = link_to " Edit", edit_expense_path(@expense), class: "btn btn-info btn-sm edit-icon"
      = link_to "All expenses", expenses_path, class: "btn btn-secondary btn-sm"
= javascript_include_tag "expenses.js"

app/views/layouts/_header.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.btn.btn-primary{:href => root_path} Expenses
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %form.form-inline.ml-auto
      - if user_signed_in?
        %a.btn.btn-primary{:href => edit_user_registration_path}
          Edit profile
        %a.btn.btn-primary.ml-2{:href => destroy_user_session_path, 'data-method': :delete}
          Log Out
      - else
        %a.btn.btn-outline-secondary{:href => new_user_session_path}
          Log In
        %a.btn.btn-primary.ml-2{:href => new_user_registration_path}
          Sign up

app/views/layouts/application.haml
<!DOCTYPE html>
%html
  %head
    %meta{charset: "UTF-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %title Expense tracker
    = csp_meta_tag
    = csrf_meta_tags
    = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css", :integrity => "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: "layouts/header"
    = yield
    %script{:crossorigin => "anonymous", :integrity => "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", :src => "https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", :src => "https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"}